# Generated by Django 4.1.5 on 2023-01-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
